"""Golden-signals quality guard for the Azure Grafana dashboards.

The live-runtime and Temporal dashboards (generated by
``scripts/gen_live_runtime_dashboard.py`` / ``scripts/gen_temporal_dashboard.py``)
are tuned for at-a-glance operability: every data panel carries a **description**
(what golden signal it is + how to read it), timeseries panels use a **table
legend** with last/max/mean calcs, and saturation/error panels carry colour
**thresholds**.

This test pins those invariants so a future regeneration can't silently drop the
polish (a panel added without a description, a legend reverted to a bare list,
the thresholds helper removed). It is complementary to the metric-name drift
guards in ``test_temporal_dashboard.py`` / ``test_dashboards_metric_names.py``.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

_AZURE_DIR = Path(__file__).resolve().parent.parent / "dashboards" / "grafana" / "azure"
_LIVE = _AZURE_DIR / "mdk-live-runtime.json"
_TEMPORAL = _AZURE_DIR / "mdk-temporal.json"

# Panel types that render data (rows are layout-only and exempt).
_DATA_PANEL_TYPES = {"timeseries", "stat", "table", "gauge", "barchart"}


def _data_panels(dashboard: dict) -> list[dict]:
    return [p for p in dashboard["panels"] if p.get("type") in _DATA_PANEL_TYPES]


@pytest.mark.unit
@pytest.mark.parametrize("path", [_LIVE, _TEMPORAL], ids=lambda p: p.name)
def test_every_data_panel_has_a_description(path: Path) -> None:
    """Each data panel carries non-trivial help text (the hover tooltip)."""
    dashboard = json.loads(path.read_text(encoding="utf-8"))
    panels = _data_panels(dashboard)
    assert panels, f"{path.name} has no data panels"
    missing = [p["title"] for p in panels if not (p.get("description") or "").strip()]
    assert not missing, f"{path.name}: panels missing a description: {missing}"
    # Descriptions should be substantive, not a one-word placeholder.
    too_short = [p["title"] for p in panels if len((p.get("description") or "").strip()) < 20]
    assert not too_short, f"{path.name}: panels with trivial descriptions: {too_short}"


@pytest.mark.unit
@pytest.mark.parametrize("path", [_LIVE, _TEMPORAL], ids=lambda p: p.name)
def test_timeseries_panels_use_table_legend_with_calcs(path: Path) -> None:
    """Timeseries panels expose last/max/mean in a table legend (golden-signals
    at-a-glance read), not a bare list."""
    dashboard = json.loads(path.read_text(encoding="utf-8"))
    ts = [p for p in dashboard["panels"] if p.get("type") == "timeseries"]
    assert ts, f"{path.name} has no timeseries panels"
    for panel in ts:
        legend = panel.get("options", {}).get("legend", {})
        assert legend.get("displayMode") == "table", (
            f"{path.name}: {panel['title']!r} legend is not table mode"
        )
        assert legend.get("calcs"), f"{path.name}: {panel['title']!r} legend has no calcs"


@pytest.mark.unit
@pytest.mark.parametrize("path", [_LIVE, _TEMPORAL], ids=lambda p: p.name)
def test_at_least_one_panel_has_thresholds(path: Path) -> None:
    """Saturation / error panels carry colour thresholds so a scan flags a panel
    that crossed an operational limit."""
    dashboard = json.loads(path.read_text(encoding="utf-8"))
    with_thresholds = [
        p
        for p in _data_panels(dashboard)
        if p.get("fieldConfig", {}).get("defaults", {}).get("thresholds")
    ]
    assert with_thresholds, f"{path.name}: no panel carries colour thresholds"
    # Each threshold config's base step must be the open-ended (None) band.
    for panel in with_thresholds:
        steps = panel["fieldConfig"]["defaults"]["thresholds"]["steps"]
        assert steps[0]["value"] is None, (
            f"{path.name}: {panel['title']!r} first threshold step must be the base band"
        )
