"""Role agents in the demo flow ship CURATED, verbose prompts.

`mdk add rag-qa` / `ticket-triager` / `code-reviewer` are the three
templates featured in the customer demo. Bundle-F polish was tight on
prompt content; this bundle expands them so prospects scanning the
files see real, opinionated role-design — not skeletal scaffolds.

The character we lock in here:

- Each prompt has an **Identity** section that names the role.
- Each prompt has a **Specialization** section that calls out what
  makes this agent CURATED and reusable (specialized skills, what
  it does NOT do, when to adapt).
- Each prompt has a **Process** + **Quality bar** + **Common
  pitfalls** structure — operator instantly sees these were
  hand-crafted, not LLM-generated minimal scaffolds.
- Each prompt has **Reuse notes** that distinguish what to keep
  vs. adapt when forking.

These tests don't check copy verbatim — they check the STRUCTURAL
markers that make the agents read as curated. Wording can evolve;
the curation pattern shouldn't quietly disappear.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from movate.templates import get_template_path

# Demo-flow templates this bundle targets. Each must contain ALL the
# structural markers. Adding a new role template to this list is the
# explicit opt-in for the verbose-prompt contract.
_VERBOSE_DEMO_TEMPLATES = (
    "rag-qa",
    "ticket-triager",
    "code-reviewer",
    "hr-policy",
)

# The structural markers that mark a prompt as a curated role agent
# rather than a skeleton scaffold. All must appear (case-sensitive,
# as Markdown headings) in every demo-flow role-agent prompt.md.
_REQUIRED_SECTIONS: tuple[str, ...] = (
    "# Identity",
    "# Specialization",
    "# Process",
    "# Quality bar",
    "# Common pitfalls",
    "# Output",
    "# Reuse notes",
)


@pytest.mark.unit
@pytest.mark.parametrize("template", _VERBOSE_DEMO_TEMPLATES)
class TestVerboseDemoPrompts:
    def test_prompt_has_all_required_sections(self, template: str) -> None:
        """Every demo-flow role agent's prompt MUST carry all the
        required Markdown section headers — that's what makes the
        file read as 'curated', not 'autogenerated stub'."""
        prompt_path = get_template_path(template) / "prompt.md"
        body = prompt_path.read_text()
        missing = [s for s in _REQUIRED_SECTIONS if s not in body]
        assert not missing, f"{template}/prompt.md missing required sections: {missing}"

    def test_prompt_is_substantially_verbose(self, template: str) -> None:
        """Verbose prompts have a floor on length — 80 lines is a
        pragmatic minimum below which the curation effort is
        obviously absent. The current files are 130+; the floor
        catches accidental truncation."""
        prompt_path = get_template_path(template) / "prompt.md"
        line_count = len(prompt_path.read_text().splitlines())
        assert line_count >= 80, (
            f"{template}/prompt.md is {line_count} lines; "
            f"expected ≥80 for a curated demo role agent"
        )

    def test_prompt_calls_out_specialization_explicitly(self, template: str) -> None:
        """The Specialization section should mention 'curated' or
        'specialized' or 'reusable' — the operator-facing signal that
        this is a role TEMPLATE, not a one-shot prompt."""
        prompt_path = get_template_path(template) / "prompt.md"
        body = prompt_path.read_text().lower()
        signals = ("curated", "specialized", "specializ", "reusable", "reuse")
        assert any(s in body for s in signals), (
            f"{template}/prompt.md doesn't mention any of {signals}"
        )

    def test_prompt_references_input_schema_fields(self, template: str) -> None:
        """Sanity check: the prompt actually USES the input it was
        given (no stub prompts that ignore their schema). Every
        verbose prompt should reference `input.` at least twice."""
        prompt_path = get_template_path(template) / "prompt.md"
        body = prompt_path.read_text()
        count = body.count("input.")
        assert count >= 2, (
            f"{template}/prompt.md references `input.` only {count} time(s); "
            f"verbose prompts should use the input schema explicitly"
        )


@pytest.mark.unit
class TestPromptsStillValidate:
    """The verbose prompts must still pass agent-load validation —
    a Jinja syntax error or schema mismatch would silently break
    the agent's first run otherwise."""

    @pytest.mark.parametrize("template", _VERBOSE_DEMO_TEMPLATES)
    def test_role_template_loads_through_load_agent(
        self,
        template: str,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """Scaffold the template into a project via `mdk init --project +
        mdk add` and round-trip through `load_agent`.

        The bare `shutil.copytree` approach fails for templates that
        declare `skills:` — `load_agent` needs the project's skill
        registry, which `mdk add` populates. Using the realistic CLI
        flow also catches any breakage introduced by the add-cmd's
        context/skill auto-scaffold logic.
        """
        from typer.testing import CliRunner  # noqa: PLC0415

        from movate.cli.main import app  # noqa: PLC0415
        from movate.core.loader import load_agent  # noqa: PLC0415

        cli = CliRunner(mix_stderr=False)
        monkeypatch.chdir(tmp_path)
        r = cli.invoke(app, ["init", "--project", "proj", "--skip-snapshot"])
        assert r.exit_code == 0, r.stdout + r.stderr
        project = tmp_path / "proj"
        monkeypatch.chdir(project)
        r = cli.invoke(app, ["add", template])
        assert r.exit_code == 0, r.stdout + r.stderr
        agent_dir = project / "agents" / template
        # If this raises, the verbose prompt broke the template.
        bundle = load_agent(agent_dir)
        assert bundle.spec.name == template
