"""LangGraph compiler — lower a WorkflowGraph IR to a Python LangGraph script.

[bold]Sprint U scaffold.[/bold] Code generation works today —
:func:`compile_langgraph` takes a :class:`WorkflowGraph` and returns
a Python source string declaring an equivalent ``langgraph.graph.StateGraph``
with one node per workflow node and one edge per workflow edge. The
generated code runs against a real LangGraph install.

What's NOT here yet (Sprint U+):

* Conditional edges — the IR doesn't model them yet (Sprint M is
  linear-only); when it does, this compiler grows ``add_conditional_edges``.
* HITL nodes — requires the IR to model human-in-the-loop wait
  states. Same story: compiler grows when IR does.
* Checkpointing — LangGraph's checkpointer protocol needs to be
  picked (in-memory? sqlite? our storage layer?). Architectural
  decision, deferred.
* State schema generation — today we emit a generic ``dict[str, Any]``
  state. Real-world workflows want typed state per node; the IR
  doesn't yet capture node-level state contracts.

Why ship the scaffold now:

* Lets the BACKLOG ``mdk export langgraph`` + ``mdk compose --runtime
  langgraph`` ergonomics land against a working compiler interface.
* Operators can preview the LangGraph shape and confirm it matches
  their mental model before Sprint U+ wires the real engine.
* The compiler API (``compile_langgraph(graph) -> str``) stays stable
  as we layer conditional / parallel / HITL in.
"""

from __future__ import annotations

from movate.core.workflow.ir import WorkflowGraph


def compile_langgraph(graph: WorkflowGraph) -> str:
    """Render a Python source file declaring a LangGraph equivalent.

    Returned string is ready to write to disk and execute. Each
    workflow node maps to a LangGraph node function that calls
    movate's executor under the hood; edges map to
    ``builder.add_edge(from, to)`` calls.

    [bold]Caller is responsible for[/bold] piping the agent-resolution
    logic into the generated code's ``__movate_call_agent`` placeholder.
    The scaffold emits a stub call so the file is syntactically valid
    Python; substituting the real call site is a Sprint U+ wiring task.
    """
    lines: list[str] = [
        '"""Auto-generated by `movate.core.workflow.compilers.langgraph`.',
        "",
        "Do not edit by hand — re-run the compiler when workflow.yaml changes.",
        "",
        f"Source workflow: {graph.name} (v{graph.version})",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any, TypedDict",
        "",
        "from langgraph.graph import END, START, StateGraph",
        "",
        "",
        "class State(TypedDict, total=False):",
        '    """Workflow state — generic for the MVP scaffold.',
        "",
        "    Sprint U+ replaces this with a typed state per node once the",
        "    IR captures node-level state contracts.",
        '    """',
        "",
        "    input: dict[str, Any]",
        "    output: dict[str, Any]",
        "",
        "",
        "def __movate_call_agent(node_id: str, state: State) -> State:",
        '    """Placeholder agent-invocation hook.',
        "",
        "    Sprint U+ wires this through the movate Executor + registry.",
        "    Today: returns the state unchanged so the generated module",
        "    is importable + walkable but not yet executable end-to-end.",
        '    """',
        "    _ = node_id  # noqa: B007 — placeholder",
        "    return state",
        "",
        "",
        "def build_graph() -> StateGraph:",
        '    """Return the LangGraph StateGraph for this workflow."""',
        "    builder = StateGraph(State)",
    ]

    # Nodes — iterate via topological order so the emitted file
    # reads in execution order. Caller code reviewers expect that.
    ordered_ids = graph.topological_order() if graph.nodes else []
    for nid in ordered_ids:
        lines.append(
            f"    builder.add_node({nid!r}, lambda s, _id={nid!r}: __movate_call_agent(_id, s))"
        )

    # Edges. The IR currently is linear, so we can emit edges in
    # topological-sort order without conditional logic.
    if ordered_ids:
        first_id = ordered_ids[0]
        last_id = ordered_ids[-1]
        lines.append(f"    builder.add_edge(START, {first_id!r})")
        for edge in graph.edges:
            lines.append(f"    builder.add_edge({edge.from_id!r}, {edge.to_id!r})")
        lines.append(f"    builder.add_edge({last_id!r}, END)")

    lines.append("    return builder")
    lines.append("")
    lines.append("")
    lines.append("if __name__ == '__main__':")
    lines.append("    graph = build_graph().compile()")
    lines.append("    print(graph)")

    return "\n".join(lines) + "\n"
