#!/usr/bin/env python3
"""Render ``ROADMAP.md`` from ``roadmap.yaml`` + ``shipped.jsonl``.

Per ADR 058 (``docs/adr/058-roadmap-calver-sync.md``), the roadmap is a
**generated, CI-freshness-gated artifact** — never hand-edited in its rendered
form. ``roadmap.yaml`` is the durable source of intent; ``shipped.jsonl`` is the
append-only, CalVer-keyed ledger of what shipped at what version. This script
joins them into ``ROADMAP.md``:

* a **Shipped** table (id · title · PR · shipped_version), **newest CalVer first**,
* an **In progress / Planned** section,
* a **Blocked-by** view derived from ``depends_on``.

Why a generator + freshness gate
--------------------------------

A hand-maintained roadmap goes stale the moment a busy session ships 14 PRs
without updating it (ADR 058's defining problem). Treating the roadmap like the
OpenAPI spec / CLI reference — generated from machine-readable truth, with a
``--check`` mode that fails CI when the committed artifact is stale — makes it
structurally incapable of drifting.

Usage
-----

    $ python scripts/gen_roadmap.py            # write ROADMAP.md
    $ python scripts/gen_roadmap.py --check     # exit 1 if ROADMAP.md is stale
    $ python scripts/gen_roadmap.py --print     # render to stdout, write nothing

CI runs ``--check`` (mirrors ``scripts/check_licenses.py`` / the
``bump_version.py --check`` freshness-gate convention). Determinism: output is a
stable function of the inputs (stable sort keys, no timestamps), so ``--check``
passes immediately after a regenerate.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
ROADMAP_YAML = REPO_ROOT / "roadmap.yaml"
SHIPPED_JSONL = REPO_ROOT / "shipped.jsonl"
ROADMAP_MD = REPO_ROOT / "ROADMAP.md"

# Generated-file banner so a human who opens ROADMAP.md knows not to hand-edit it.
_BANNER = (
    "<!-- GENERATED by scripts/gen_roadmap.py from roadmap.yaml + shipped.jsonl.\n"
    "     Do NOT edit by hand — edit roadmap.yaml and run "
    "`python scripts/gen_roadmap.py`.\n"
    "     CI gates freshness via `gen_roadmap.py --check` (ADR 058). -->"
)

# Statuses that count as not-yet-shipped, in render order.
_OPEN_STATUSES = ("in_progress", "planned")
_STATUS_LABEL = {
    "in_progress": "In progress",
    "planned": "Planned",
    "dropped": "Dropped",
}


def _version_key(version: str) -> tuple[int, ...]:
    """Parse a CalVer ``YYYY.M.D.N`` string into an int tuple for ordering.

    Unparseable components fall back to ``0`` so a malformed version sorts
    last-ish rather than crashing the render (the data is validated elsewhere).
    """
    parts: list[int] = []
    for chunk in str(version).split("."):
        parts.append(int(chunk) if chunk.isdigit() else 0)
    return tuple(parts)


def _load_yaml(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise SystemExit(f"{path.name}: expected a mapping at the top level")
    return data


def _load_items(path: Path) -> list[dict[str, Any]]:
    data = _load_yaml(path)
    items = data.get("items", [])
    if not isinstance(items, list):
        raise SystemExit(f"{path.name}: 'items' must be a list")
    for item in items:
        if not isinstance(item, dict) or "id" not in item:
            raise SystemExit(f"{path.name}: every item needs an 'id' (got {item!r})")
    return items


def _load_ledger(path: Path) -> list[dict[str, Any]]:
    """Parse the append-only ``shipped.jsonl`` ledger (one JSON object per line)."""
    if not path.is_file():
        return []
    rows: list[dict[str, Any]] = []
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError as exc:
            raise SystemExit(f"{path.name}:{lineno}: invalid JSON ({exc})") from exc
        if not isinstance(obj, dict):
            raise SystemExit(f"{path.name}:{lineno}: expected a JSON object")
        rows.append(obj)
    return rows


def _md_escape(text: str) -> str:
    """Escape the one Markdown-table metachar that can break a cell: the pipe."""
    return str(text).replace("|", "\\|")


def _shipped_version_of(item: dict[str, Any], ledger_version: dict[Any, Any]) -> str:
    """The CalVer an item shipped at, preferring the ledger (ground truth)
    and falling back to roadmap.yaml's projected ``shipped_version`` field."""
    return str(ledger_version.get(item["id"], item.get("shipped_version", "")))


def _shipped_pr_of(item: dict[str, Any], ledger_pr: dict[Any, Any]) -> Any:
    """The PR that delivered an item (ledger first, then roadmap.yaml)."""
    return ledger_pr.get(item["id"], item.get("pr", ""))


def _render_shipped(
    items: list[dict[str, Any]],
    ledger_version: dict[Any, Any],
    ledger_pr: dict[Any, Any],
) -> list[str]:
    """The **Shipped** table, newest CalVer first (D5 ordering contract)."""
    shipped = [i for i in items if i.get("status") == "shipped"]
    # Stable, deterministic order: CalVer desc, then PR desc, with id asc as a
    # final tiebreaker (so equal CalVer+PR — shouldn't happen — never churns).
    # Built by layering sorts: the last sort applied is the primary key.
    shipped.sort(key=lambda i: str(i["id"]))
    shipped.sort(
        key=lambda i: (
            _version_key(_shipped_version_of(i, ledger_version)),
            _shipped_pr_of(i, ledger_pr) or 0,
        ),
        reverse=True,
    )

    lines = ["## Shipped", ""]
    if not shipped:
        lines += ["_Nothing shipped yet._", ""]
        return lines
    lines += ["| id | title | PR | shipped_version |", "| --- | --- | --- | --- |"]
    for item in shipped:
        pr = _shipped_pr_of(item, ledger_pr)
        pr_cell = f"#{pr}" if pr not in ("", None) else ""
        lines.append(
            f"| `{_md_escape(item['id'])}` "
            f"| {_md_escape(item.get('title', ''))} "
            f"| {pr_cell} "
            f"| {_md_escape(_shipped_version_of(item, ledger_version))} |"
        )
    lines.append("")
    return lines


def _render_open(items: list[dict[str, Any]]) -> list[str]:
    """The **In progress / Planned** section, grouped by status, id-sorted."""
    lines = ["## In progress / Planned", ""]
    open_items = [i for i in items if i.get("status") in _OPEN_STATUSES]
    if not open_items:
        return [*lines, "_Nothing in progress or planned._", ""]
    for status in _OPEN_STATUSES:
        bucket = sorted(
            (i for i in open_items if i.get("status") == status),
            key=lambda i: str(i["id"]),
        )
        if not bucket:
            continue
        lines += [f"### {_STATUS_LABEL[status]}", ""]
        for item in bucket:
            adr = item.get("adr")
            adr_suffix = f" (ADR {adr})" if adr else ""
            lines.append(
                f"- `{_md_escape(item['id'])}` — {_md_escape(item.get('title', ''))}{adr_suffix}"
            )
        lines.append("")
    return lines


def _render_blocked(items: list[dict[str, Any]]) -> list[str]:
    """The **Blocked-by** view: open items with unshipped ``depends_on`` deps."""
    by_id = {item["id"]: item for item in items}
    lines = [
        "## Blocked-by",
        "",
        "Items with unshipped dependencies (from `depends_on`).",
        "",
    ]
    blocked: list[tuple[str, list[str]]] = []
    for item in sorted(items, key=lambda i: str(i["id"])):
        if item.get("status") == "shipped":
            continue
        unshipped = sorted(
            str(dep)
            for dep in (item.get("depends_on") or [])
            if by_id.get(dep, {}).get("status") != "shipped"
        )
        if unshipped:
            blocked.append((str(item["id"]), unshipped))
    if not blocked:
        return [*lines, "_Nothing blocked._", ""]
    for item_id, deps in blocked:
        dep_list = ", ".join(f"`{_md_escape(d)}`" for d in deps)
        lines.append(f"- `{_md_escape(item_id)}` blocked by {dep_list}")
    lines.append("")
    return lines


def render(items: list[dict[str, Any]], ledger: list[dict[str, Any]]) -> str:
    """Render the full ROADMAP.md body. Pure function of its inputs."""
    # shipped fields per id, preferring the ledger (the CalVer ground truth).
    ledger_version = {row.get("id"): row.get("version") for row in ledger if row.get("id")}
    ledger_pr = {row.get("id"): row.get("pr") for row in ledger if row.get("id")}

    lines: list[str] = [
        _BANNER,
        "",
        "# Roadmap",
        "",
        "Generated from `roadmap.yaml` (intent) + `shipped.jsonl` "
        "(CalVer-keyed ship ledger). See "
        "[ADR 058](docs/adr/058-roadmap-calver-sync.md).",
        "",
    ]
    lines += _render_shipped(items, ledger_version, ledger_pr)
    lines += _render_open(items)
    lines += _render_blocked(items)

    # Single trailing newline; no churning whitespace.
    return "\n".join(lines).rstrip("\n") + "\n"


def _build() -> str:
    items = _load_items(ROADMAP_YAML)
    ledger = _load_ledger(SHIPPED_JSONL)
    return render(items, ledger)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the committed ROADMAP.md differs from a fresh render.",
    )
    parser.add_argument(
        "--print",
        action="store_true",
        dest="print_only",
        help="Render to stdout without writing ROADMAP.md.",
    )
    args = parser.parse_args()

    rendered = _build()

    if args.print_only:
        sys.stdout.write(rendered)
        return 0

    if args.check:
        current = ROADMAP_MD.read_text(encoding="utf-8") if ROADMAP_MD.is_file() else ""
        if current != rendered:
            print(
                "✗ ROADMAP.md is stale — it does not match roadmap.yaml / "
                "shipped.jsonl.\n"
                "  Regenerate it with:  python scripts/gen_roadmap.py\n"
                "  (then commit ROADMAP.md). See ADR 058.",
                file=sys.stderr,
            )
            return 1
        print("✓ ROADMAP.md is up to date.")
        return 0

    ROADMAP_MD.write_text(rendered, encoding="utf-8")
    print(f"wrote {ROADMAP_MD.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
